import * as tape from 'tape';
import * as index from "../../../src/lib";

tape('library index', ({same, end}) => {
    const expected: Array<string> = [
        'isATwingError',
        'createTemplateLoadingError', 'isATemplateLoadingError',
        'createRuntimeError', 'isARuntimeError',
        'createParsingError',
        'createFilesystemLoader',
        'createArrayLoader',
        'createChainLoader',
        'createMarkup', 'isAMarkup',
        'createApplyNode', 'applyNodeType',
        'createAutoEscapeNode', 'autoEscapeNodeType',
        'createBlockNode',
        'createBodyNode', 'blockNodeType',
        'createCheckSecurityNode',
        'createCheckToStringNode',
        'createCommentNode',
        'createDeprecatedNode',
        'createDoNode',
        'createFlushNode',
        'createForNode',
        'createForLoopNode',
        'createIfNode',
        'createImportNode',
        'createBaseIncludeNode',
        'createLineNode',
        'createMacroNode',
        'createTemplateNode', 'templateNodeType',
        'createSandboxNode', 'sandboxNodeType',
        'createSetNode',
        'createTraitNode',
        'createWithNode',
        'createBaseArrayNode', 'createArrayNode',
        'createArrowFunctionNode',
        'createAssignmentNode', 'assignmentNodeType',
        'createAttributeAccessorNode',
        'createBaseBinaryNode',
        'createBlockFunctionNode', 'blockFunctionNodeType',
        'createBaseCallNode',
        'createBaseConditionalNode', 'createConditionalNode', 'conditionalNodeType',
        'createConstantNode',
        'createEscapeNode',
        'createHashNode', 'hashNodeType',
        'createMethodCallNode', 'methodCallNodeType',
        'createNameNode', 'nameNodeType',
        'createNullishCoalescingNode', 'nullishCoalescingNodeType',
        'createParentFunctionNode', 'parentFunctionNodeType',
        'createBaseUnaryNode',
        'createAddNode', 'addNodeType',
        'createAndNode', 'andNodeType',
        'createBitwiseAndNode', 'bitwiseAndNodeType',
        'createBitwiseOrNode', 'bitwiseOrNodeType',
        'createBitwiseXorNode', 'bitwiseXorNodeType',
        'createConcatenateNode', 'concatenateNodeTYpe',
        'createDivideAndFloorNode', 'divideAndFloorNodeType',
        'createDivideNode', 'divideNodeType',
        'createEndsWithNode',
        'createIsEqualNode',
        'createIsGreaterThanNode',
        'createIsGreaterThanOrEqualToNode',
        'createIsInNode',
        'createIsLessThanNode',
        'createIsLessThanOrEqualToNode',
        'createIsNotEqualToNode',
        'createIsNotInNode',
        'createMatchesNode',
        'createModuloNode',
        'createMultiplyNode',
        'createOrNode',
        'createPowerNode',
        'createRangeNode',
        'createStartsWithNode',
        'createSubtractNode',
        'createFilterNode', 'filterNodeType',
        'createFunctionNode', 'functionNodeType',
        'createTestNode', 'testNodeType',
        'createNegativeNode', 'negativeNodeType',
        'createNotNode', 'notNodeType',
        'createPositiveNode', 'positiveNodeType',
        'createEmbedNode', 'embedNodeType',
        'createIncludeNode', 'includeNodeType',
        'createBlockReferenceNode', 'blockReferenceType',
        'createPrintNode', 'printNodeType',
        'createSpacelessNode', 'spacelessNodeType',
        'createTextNode', 'textNodeType',
        'createVerbatimNode', 'verbatimNodeType',
        'createApplyTagHandler',
        'createAutoEscapeTagHandler',
        'createBlockTagHandler',
        'createDeprecatedTagHandler',
        'createDoTagHandler',
        'createEmbedTagHandler',
        'createExtendsTagHandler',
        'createFilterTagHandler',
        'createFlushTagHandler',
        'createForTagHandler',
        'createFromTagHandler',
        'createIfTagHandler',
        'createImportTagHandler',
        'createIncludeTagHandler',
        'createLineTagHandler',
        'createMacroTagHandler',
        'createSandboxTagHandler',
        'createSetTagHandler',
        'createSpacelessTagHandler',
        'createUseTagHandler',
        'createVerbatimTagHandler',
        'createWithTagHandler',
        'createBaseNode', 'getChildren', 'getChildrenCount',
        'createEnvironment',
        'createExtensionSet',
        'createFilter',
        'createFunction',
        'createLexer',
        'createOperator',
        'createSandboxSecurityPolicy',
        'createSource',
        'createSourceMapRuntime',
        'createTemplate',
        'createTest'
    ];

    const propertyNames = Object.getOwnPropertyNames(index).filter((name) => name !== '__esModule');

    for (const key of expected) {
        same(propertyNames.includes(key), true, `${key} is exported by the index`);
    }

    for (const key of propertyNames) {
        same(expected.includes(key), true, `${key} is legit in the index`);
    }

    end();
});
