import tape from "tape";
import * as index from "../../main/lib.js";

tape('library index', ({same, end}) => {
    const expected: Array<string> = [
        'isATwingError',
        'createTemplateLoadingError',
        'createRuntimeError',
        'createParsingError',
        'createFilesystemLoader', 'createSynchronousFilesystemLoader',
        'createArrayLoader', 'createSynchronousArrayLoader',
        'createChainLoader', 'createSynchronousChainLoader',
        'createMarkup', 'isAMarkup',
        'createApplyNode',
        'createAutoEscapeNode',
        'createBlockNode',
        'createCheckSecurityNode',
        'createCheckToStringNode',
        'createCommentNode',
        'createDeprecatedNode',
        'createDoNode',
        'createFlushNode',
        'createForNode',
        'createForLoopNode',
        'createIfNode',
        'createImportNode',
        'createBaseIncludeNode',
        'createLineNode',
        'createMacroNode',
        'createTemplateNode',
        'createSandboxNode',
        'createSetNode',
        'createTraitNode',
        'createWithNode',
        'createBaseArrayNode', 'createArrayNode',
        'createArrowFunctionNode',
        'createAssignmentNode',
        'createAttributeAccessorNode',
        'createBaseBinaryNode',
        'createBlockFunctionNode',
        'createBaseCallNode',
        'createBaseConditionalNode', 'createConditionalNode',
        'createConstantNode',
        'createEscapeNode',
        'createHashNode',
        'createMethodCallNode',
        'createNameNode',
        'createNullishCoalescingNode',
        'createParentFunctionNode',
        'createSpreadNode',
        'createBaseUnaryNode',
        'createAddNode',
        'createAndNode',
        'createBitwiseAndNode',
        'createBitwiseOrNode',
        'createBitwiseXorNode',
        'createConcatenateNode',
        'createDivideAndFloorNode',
        'createDivideNode',
        'createEndsWithNode',
        'createHasEveryNode',
        'createHasSomeNode',
        'createIsEqualNode',
        'createIsGreaterThanNode',
        'createIsGreaterThanOrEqualToNode',
        'createIsInNode',
        'createIsLessThanNode',
        'createIsLessThanOrEqualToNode',
        'createIsNotEqualToNode',
        'createIsNotInNode',
        'createMatchesNode',
        'createModuloNode',
        'createMultiplyNode',
        'createOrNode',
        'createPowerNode',
        'createRangeNode',
        'createStartsWithNode',
        'createSubtractNode',
        'createFilterNode',
        'createFunctionNode',
        'createTestNode',
        'createNegativeNode',
        'createNotNode',
        'createPositiveNode',
        'createEmbedNode',
        'createIncludeNode',
        'createBlockReferenceNode',
        'createPrintNode',
        'createSpacelessNode',
        'createTextNode',
        'createVerbatimNode',
        'createApplyTagHandler',
        'createAutoEscapeTagHandler',
        'createBlockTagHandler',
        'createDeprecatedTagHandler',
        'createDoTagHandler',
        'createEmbedTagHandler',
        'createExtendsTagHandler',
        'createFilterTagHandler',
        'createFlushTagHandler',
        'createForTagHandler',
        'createFromTagHandler',
        'createIfTagHandler',
        'createImportTagHandler',
        'createIncludeTagHandler',
        'createLineTagHandler',
        'createMacroTagHandler',
        'createSandboxTagHandler',
        'createSetTagHandler',
        'createSpacelessTagHandler',
        'createUseTagHandler',
        'createVerbatimTagHandler',
        'createWithTagHandler',
        'createBaseNode',
        'createNode',
        'getChildren',
        'getChildrenCount',
        'createEnvironment', 'createSynchronousEnvironment',
        'createExtensionSet',
        'createFilter', 'createSynchronousFilter',
        'createFunction', 'createSynchronousFunction',
        'createLexer',
        'createOperator',
        'createSandboxSecurityPolicy',
        'createSource',
        'createSourceMapRuntime',
        'createTemplate', 'createSynchronousTemplate',
        'createTest', 'createSynchronousTest',
        'executeNode', 'executeNodeSynchronously',
        'createTemplateLoader', 'createSynchronousTemplateLoader',
        'createContext',
        'createOutputBuffer',
        'include', 'includeSynchronously',
        'getTraceableMethod', 'getSynchronousTraceableMethod',
        'iteratorToMap', 'iterableToMap',
        'mergeIterables'
    ];

    const propertyNames = Object.getOwnPropertyNames(index).filter((name) => name !== '__esModule');

    for (const key of expected) {
        same(propertyNames.includes(key), true, `${key} is exported by the index`);
    }
    
    for (const key of propertyNames) {
        same(expected.includes(key), true, `${key} is legit in the index`);
    }
    
    end();
});
