import * as tape from 'tape';
import * as mainIndex from "../../../../src/main";
import * as browserIndex from "../../../../src/browser";

tape('main and browser indexes', (test) => {
    let expected = [
        'TwingBaseNodeVisitor',
        'TwingCacheFilesystem',
        'TwingCacheNull',
        'TwingCompiler',
        'TwingEnvironment',
        'TwingError',
        'TwingErrorLoader',
        'TwingErrorRuntime',
        'TwingErrorSyntax',
        'TwingExtension',
        'TwingExtensionCore',
        'TwingExtensionSet',
        'TwingFilter',
        'TwingFunction',
        'TwingLexer',
        'TwingLoaderArray',
        'TwingLoaderChain',
        'TwingLoaderFilesystem',
        'TwingLoaderNull',
        'TwingLoaderRelativeFilesystem',
        'TwingMarkup',
        'TwingNode',
        'createAutoEscapeNode',
        'createBlockNode',
        'createBlockReferenceNode',
        'createBodyNode',
        'createCheckSecurityNode',
        'createCommentNode',
        'createDeprecatedNode',
        'createDoNode',
        'createEmbedNode',
        'createBaseExpressionNode',
        'createArrayNode',
        'createAssignNameNode',
        'createBaseBinaryNode',
        'createAddNode',
        'createAndNode',
        'createBitwiseAndNode',
        'createBitwiseOrNode',
        'createBitwiseXOrNode',
        'createConcatNode',
        'createDivNode',
        'createBinaryEndsWithNode',
        'createEqualNode',
        'createFloorDivNode',
        'createGreaterThanNode',
        'createGreaterThanOrEqualToNode',
        'createInNode',
        'createLessThanNode',
        'createLessThanOrEqualToNode',
        'createMatchesNode',
        'createModuloNode',
        'createMultiplyNode',
        'createNotEqualToNode',
        'createNotInNode',
        'createOrNode',
        'createPowerNode',
        'createRangeNode',
        'createStartsWithNode',
        'createSubtractNode',
        'createBlockReferenceNode',
        'createBaseCallNode',
        'createConditionalNode',
        'createConstantNode',
        'createFilterNode',
        'createDefaultFilterNode',
        'createFunctionNode',
        'createGetAttributeNode',
        'createHashNode',
        'createMethodCallNode',
        'createNameNode',
        'createNullCoalesceNode',
        'createParentNode',
        'createTestNode',
        'createConstantTestNode',
        'createDefinedTestNode',
        'createBaseUnaryNode',
        'createNegativeNode',
        'createNotNode',
        'createPositiveNode',
        'createFlushNode',
        'createForNode',
        'createForLoopNode',
        'createIfNode',
        'createImportNode',
        'createIncludeNode',
        'createMacroNode',
        'createModuleNode',
        'createPrintNode',
        'createSandboxNode',
        'createSandboxedPrintNode',
        'createSetNode',
        'createSpacelessNode',
        'createTextNode',
        'TwingNodeTraverser',
        'createVerbatimNode',
        'TwingNodeVisitorEscaper',
        'TwingNodeVisitorSafeAnalysis',
        'TwingNodeVisitorSandbox',
        'createWithNode',
        'TwingOperator',
        'TwingOperatorType',
        'TwingOperatorAssociativity',
        'TwingOutputBuffer',
        'TwingOutputHandler',
        'TwingParser',
        'TwingSandboxSecurityError',
        'TwingSandboxSecurityNotAllowedFilterError',
        'TwingSandboxSecurityNotAllowedFunctionError',
        'TwingSandboxSecurityNotAllowedMethodError',
        'TwingSandboxSecurityNotAllowedPropertyError',
        'TwingSandboxSecurityNotAllowedTagError',
        'TwingSandboxSecurityPolicy',
        'TwingSource',
        'TwingSourceMapNode',
        'TwingSourceMapNodeFactory',
        'TwingSourceMapNodeFactorySpaceless',
        'TwingSourceMapNodeSpaceless',
        'TwingTemplate',
        'TwingTest',
        'TwingTokenParser',
        'TwingTokenParserAutoEscape',
        'TwingTokenParserBlock',
        'TwingTokenParserDo',
        'TwingTokenParserEmbed',
        'TwingTokenParserExtends',
        'TwingTokenParserFilter',
        'TwingTokenParserFlush',
        'TwingTokenParserFor',
        'TwingTokenParserFrom',
        'TwingTokenParserIf',
        'TwingTokenParserImport',
        'TwingTokenParserInclude',
        'TwingTokenParserMacro',
        'TwingTokenParserSandbox',
        'TwingTokenParserSet',
        'TwingTokenParserSpaceless',
        'TwingTokenParserUse',
        'TwingTokenParserVerbatim',
        'TwingTokenParserWith',
        'TwingTokenStream'
    ];

    for (let key of expected) {
        test.true(Reflect.has(mainIndex, key), `${key} is exported by main index`);
        test.true(Reflect.has(browserIndex, key), `${key} is exported by browser index`);
    }

    for (let key in mainIndex) {
        test.true(expected.includes(key), `${key} is legit in main index`);
    }

    for (let key in browserIndex) {
        test.true(expected.includes(key), `${key} is legit in browser index`);
    }

    test.same(browserIndex.TwingLoaderFilesystem.name, 'TwingLoaderNull', 'browser export of TwingLoaderRelativeFilesystem is a noop');
    test.same(browserIndex.TwingLoaderRelativeFilesystem.name, 'TwingLoaderNull', 'browser export of TwingLoaderRelativefilesystem is a noop');
    test.same(browserIndex.TwingCacheFilesystem.name, 'TwingCacheNull', 'browser export of TwingCacheFilesystem is a noop');

    test.end();
});
